services:
  frontend:
    container_name: rechargeable_battery_management_frontend
    build: ./frontend
    image: rechargeable-battery-management-frontend:latest
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  app:
    container_name: rechargeable_battery_management_app
    build: ./app
    image: rechargeable-battery-management-app:latest
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rechargeable_battery_management
      SPRING_DATASOURCE_USERNAME: $DB_USER
      SPRING_DATASOURCE_PASSWORD: $DB_PASSWORD
    depends_on:
      - db

  db:
    container_name: rechargeable_battery_management_db
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: rechargeable_battery_management
